baseURL = "https://rijschoolattent.nl/"
languageCode = "nl-nl"
title = "Rijschool Attent Hengelo"
theme = "attent"

[params]
  description = "Rijschool Attent Hengelo - Persoonlijke rijlessen in Hengelo en omgeving"
  author = "Rijschool Attent"
  contact_email = "info@rijschoolattent.nl"
  contact_phone = "06-12345678"

[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "Over ons"
    url = "/over-ons/"
    weight = 2
  [[menu.main]]
    name = "Tarieven"
    url = "/tarieven/"
    weight = 3
  [[menu.main]]
    name = "Contact"
    url = "/contact/"
    weight = 4
